### ISSUE TITLE
installation trouble

### ISSUE THREAD

**Issue by KSAMissionCtrl** [truemetro/kiag-niagara#1]
I dropped the folder airport-kiag-niagra into my Community folder but the results are that KIAG still lacks buildings and Niagara Falls doesn't look any different than it already did (on Ultra settings):

![1250410_20200913111320_1](https://user-images.githubusercontent.com/18425575/93021750-84401f00-f5b2-11ea-85de-c98062a94517.png)
![1250410_20200913111354_1](https://user-images.githubusercontent.com/18425575/93021752-84401f00-f5b2-11ea-997d-7db107da291a.png)

I've installed a scenery add-on that puts the casino buildings into Atlantic City and a mod that removes the toolbar icon from the top of the screen and both worked fine after dropping them into the Community folder so not sure what I'm doing wrong here

**Comment by truemetro** [comment]
Oops. first of all this github is not updated with my current progress, but I beleive there should be at least some improvement, I'll update the version on github in any case.

However I believe the problem you're having is that the master branch contains the project file structure not just the release, instead of putting the entire airport-kiag-niagara folder into Community, go inside it to airport-kiag-niagara/Packages and there should be "truemetro-airport-kiag-niagara." put that in Community.

as I said before though this is an earlier version.

**Comment by truemetro** [comment]
Okay, I added an alpha release to master which should have the latest work and also will just be the file to be placed in Community rather than the dev filestructure. Thanks for your interest!

**Comment by KSAMissionCtrl** [comment]
okay thanks, did not realize this wasn't done or ready for release. Looks great so far. I got linked here from https://www.flightsim.com/vbfs/fslib.php?searchid=79981136

**Comment by truemetro** [comment]
Good to know, the link doesn't seem to work for me but it may just be that I'm on mobile.

**Comment by KSAMissionCtrl** [comment]
no it doesn't work for me either, it's not a perma link like I thought. Anyways, that file library is where I found this scenery is what I wanted you to know

**Comment by truemetro** [comment]
alright, good to know, interesting that people found this github relatively quickly. I've been posting about my progress but I've never linked here. anyway, hope it works for you now, it will get better. Currently I'm waiting on some changes to the SDK which will allow me to add some life to the falls, namely in the form of clouds of spray at the bottom.
